stages:
  - build
  - release

# variables:
#   CARGO_HOME: $CI_PROJECT_DIR/cargo_home

# default:
#   image: rust:latest
#   before_script:
#     - export PATH="$PATH:$CARGO_HOME/bin"
#     - mdbook --version || cargo install --debug mdbook

# cache:
#   paths:
#     - $CARGO_HOME/bin
image: python:alpine

before_script:
  - pip install mkdocs


build:
  stage: build
  script:
    - make build


pages:
  stage: release
  only:
    - master
  script:
    - make build
    - mv dist public
  artifacts:
    paths:
      - public
