# [package]
# name = "kernel"
# version = "0.1.3"
# authors = ["z0mbie42 <sylvain@kerkour.com>"]
# edition = "2018"
# homepage = "https://bloom.sh"
# repository = "https://github.com/bloom42/kernel.git"
# description = "Open internet services"
# keywords = ["bloom"]
# license = "MPL-2.0"
# publish = false


# [dependencies]
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# diesel = { version = "1.4", features = ["postgres", "chrono", "serde_json", "r2d2", "uuidv07"] }
# actix = "0.7"
# actix-web = "0.7.19"
# http = "0.1.0"
# dotenv = "^0.13.0"
# chrono = { version = "0.4", features = ["serde"] }
# futures = "0.1"
# uuid = { version = "0.7", features = ["serde", "v4"] }
# rand = "0.6"
# failure = "0.1.5"
# diesel_as_jsonb = { path = "crates/diesel_as_jsonb" }
# bcrypt = { path = "crates/bcrypt-rs" }
# hex = { path = "crates/hex-rs" }
# eventsourcing = { path = "crates/eventsourcing-rs" }
# lettre = "0.8"
# lettre_email = "0.8"
# num_cpus = "1.0"
# handlebars = "2.0.0-beta.1"
# base64 = "0.10.1"
# mimesniff = { path = "crates/mimesniff-rs" }
# mime = "0.3"
# image = "0.21"

# # lazy_static = "1.3.0"

# # AWS libs
# rusoto_core = "0.37"
# rusoto_s3 = "0.37"

# tokio-timer = "0.2"

# # error tracking
# sentry = "0.12.0"



# [profile.release]
# # for error tracking
# debug = true
# lto = true


[workspace]
members = [
    "crates/diesel_as_jsonb",
    "crates/sendgrid-rs",
    "crates/bcrypt-rs",
    "crates/hex-rs",
    "crates/eventsourcing-rs",
    "crates/mimesniff-rs",

    "bloom/kernel",
    "bloom/notes",
    "bloom/contacts",
    # "bloom/api",
]
