language: rust
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --no-default-features --verbose
  - cargo test --no-default-features --verbose
  - (cd dotenv_codegen; cargo build --verbose)
  - (cd dotenv_codegen; cargo test --verbose)
