[Settings]


[build]
  publish = "public/"


[[redirects]]
  from = "https://peaceful-nightingale-b3e4cb.netlify.com/*"
  to = "https://www.bloom.sh/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bloom.sh/*"
  to = "https://www.bloom.sh/:splat"
  status = 301
  force = true


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "X-Download-Options" = "noopen"
    "X-Frame-Options" = "DENY"
    "Referrer-Policy" = "same-origin"
    "Expect-CT" = "max-age=86400; enforce"
    "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
