[package]
name = "diesel_uuid"
version = "0.1.0"
authors = ["z0mbie42 <sylvain@kerkour.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = ["uuid", "postgres"] }
diesel_derives = { version = "1.3.0" }
uuid = { version = "0.7", features = ["serde"] }
serde = "1.0.80"
serde_derive = "1.0.80"
