# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
  - schema.graphql

exec:
  filename: api/graphql/generated.go

model:
  filename: api/graphql/model/models_gen.go

models:
  ID:
    model: gitlab.com/bloom42/bloom/server/api/graphql/model.ID
  Int64:
    model: gitlab.com/bloom42/bloom/server/api/graphql/model.Int64
  Bytes:
    model: gitlab.com/bloom42/bloom/server/api/graphql/model.Bytes


resolver:
  filename: api/graphql/resolver.go
  type: Resolver

autobind:
  - gitlab.com/bloom42/bloom/server/api/graphql/model
