[package]
name = "bloom_messages"
version = "0.1.0"
authors = ["z0mbie42 <sylvain@kerkour.fr>"]
edition = "2018"
license = "AGPL-3.0"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
