[package]
name = "mimesniff"
version = "0.2.1"
authors = ["z0mbie42 <sylvain@kerkour.com>"]
edition = "2018"
homepage = "https://gitlab.com/bloom42/bloom"
repository = "https://gitlab.com/bloom42/bloom.git"
description = "Determine the Content-Type of the given data"
keywords = ["bloom", "content-type", "mime", "mimesniff"]
license = "Apache-2.0"

[dependencies]
mime = "0.3"
