[Settings]


[build]
  publish = "dist/"


# rewrite to for vuejs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "https://bloom.sh/*"
  to = "https://bloom.sh/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bloom42.com/*"
  to = "https://bloom.sh/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://qi-lang.org/*"
  to = "https://bloom.sh/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.qi-lang.org/*"
  to = "https://bloom.sh/:splat"
  status = 301
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "X-Download-Options" = "noopen"
    "X-Frame-Options" = "DENY"
    "Referrer-Policy" = "same-origin"
    "Expect-CT" = "max-age=86400; enforce"
    "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
